/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GroupChatRouteImport } from './routes/group-chat'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CallsRouteImport } from './routes/calls'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupChatRoute = GroupChatRouteImport.update({
  id: '/group-chat',
  path: '/group-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CallsRoute = CallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calls': typeof CallsRoute
  '/chat': typeof ChatRoute
  '/discover': typeof DiscoverRoute
  '/faq': typeof FaqRoute
  '/group-chat': typeof GroupChatRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/stories': typeof StoriesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calls': typeof CallsRoute
  '/chat': typeof ChatRoute
  '/discover': typeof DiscoverRoute
  '/faq': typeof FaqRoute
  '/group-chat': typeof GroupChatRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/stories': typeof StoriesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calls': typeof CallsRoute
  '/chat': typeof ChatRoute
  '/discover': typeof DiscoverRoute
  '/faq': typeof FaqRoute
  '/group-chat': typeof GroupChatRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/stories': typeof StoriesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/calls'
    | '/chat'
    | '/discover'
    | '/faq'
    | '/group-chat'
    | '/login'
    | '/privacy'
    | '/profile'
    | '/settings'
    | '/stories'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/calls'
    | '/chat'
    | '/discover'
    | '/faq'
    | '/group-chat'
    | '/login'
    | '/privacy'
    | '/profile'
    | '/settings'
    | '/stories'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/calls'
    | '/chat'
    | '/discover'
    | '/faq'
    | '/group-chat'
    | '/login'
    | '/privacy'
    | '/profile'
    | '/settings'
    | '/stories'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CallsRoute: typeof CallsRoute
  ChatRoute: typeof ChatRoute
  DiscoverRoute: typeof DiscoverRoute
  FaqRoute: typeof FaqRoute
  GroupChatRoute: typeof GroupChatRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  StoriesRoute: typeof StoriesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group-chat': {
      id: '/group-chat'
      path: '/group-chat'
      fullPath: '/group-chat'
      preLoaderRoute: typeof GroupChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calls': {
      id: '/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof CallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CallsRoute: CallsRoute,
  ChatRoute: ChatRoute,
  DiscoverRoute: DiscoverRoute,
  FaqRoute: FaqRoute,
  GroupChatRoute: GroupChatRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  StoriesRoute: StoriesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
